-- 설문조사 객관식 "기타" 옵션 기능 추가
-- 실행 대상: SURVEY_ITEM, SURVEY_ANSWER 테이블

-- SURVEY_ITEM: 기타 항목 여부 및 입력 안내 문구
ALTER TABLE SURVEY_ITEM ADD COLUMN OTHER_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '기타 항목 여부' AFTER JUMP_QUESTION;
ALTER TABLE SURVEY_ITEM ADD COLUMN OTHER_PLACEHOLDER VARCHAR(200) DEFAULT NULL COMMENT '기타 항목 입력 안내 문구' AFTER OTHER_YN;

-- SURVEY_ANSWER: 기타 항목 텍스트
ALTER TABLE SURVEY_ANSWER ADD COLUMN OTHER_TEXT VARCHAR(2000) DEFAULT NULL COMMENT '기타 항목 텍스트' AFTER ANSWER;
