# port Configuration
server.port=8100

# ============================================
# Primary Database (System/Member DB)
# ============================================
spring.datasource.primary.jdbc-url=jdbc:mariadb://localhost:3307/wise_ad
spring.datasource.primary.username=root
spring.datasource.primary.password=root1234!
spring.datasource.primary.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.primary.hikari.maximum-pool-size=10
spring.datasource.primary.hikari.minimum-idle=5
spring.datasource.primary.hikari.idle-timeout=30000
spring.datasource.primary.hikari.connection-timeout=20000

# ============================================
# SMS Database (Messaging Module DB)
# ============================================
spring.datasource.sms.jdbc-url=jdbc:mariadb://127.0.0.1:3306/monkeys
spring.datasource.sms.username=root
spring.datasource.sms.password=root1234
spring.datasource.sms.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.sms.hikari.maximum-pool-size=8
spring.datasource.sms.hikari.minimum-idle=2
spring.datasource.sms.hikari.idle-timeout=10000
spring.datasource.sms.hikari.connection-timeout=20000



# Hiworks Email Settings
mail.hiworks.url=https://api.hiworks.com
mail.hiworks.id=service
mail.hiworks.office-token=647eaf6e7244247ce1dba5e99cc81304